### ISSUE TITLE
Failure to handle relative links

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ets-ogcapi-features10#131] opened 2021-01-21 21:51 UTC
My understanding is that links to OGC API resources should follow RFC 8288 ( https://tools.ietf.org/html/rfc8288 ) and RFC 3986 ( https://tools.ietf.org/html/rfc3986 ) allowing for relative links.
However the test seems to require absolute links and not be able to resolve relative links to the different resources (e.g. the /api, /conformance, /collections, /items).

**Comment by dstenger** [comment] 2021-01-25 11:20
Thank you for reporting.

You are probably referring to the path section of the OpenAPI document?
The test suite should be capable to resolve relative links there.

Can you please describe your problem more in detail? Is a test service available to reproduce your problem?

**Comment by jerstlouis** [comment] 2021-01-25 13:04
@dstenger No, I am referring to links in the different JSON document of the API itself, not its OpenAPI definition.

e.g. on the landing page (links to the /api, /conformance and /collections), and on the collection description pages (links to items).

The service in question has been tweaked to use absolute paths where the test suite was not able to handle relative links, but we could revert to relative path to re-test once it is improved.

**Comment by jerstlouis** [comment] 2021-02-18 15:18
@dstenger I can revert our test service to feature the problem again, providing this is OK with the compliance program? (we did get our compliance status) @ghobona

**Comment by ghobona** [comment] 2021-02-25 09:22
Upon closer reflection, this issue appears to be resolved. The service was modified to comply with the test and a certificate has been issued. So I am proceeding to close the ticket.

**Comment by jerstlouis** [comment] 2021-02-25 09:31
@ghobona The issue is not resolved.
This is an important issue, clients should be able to handle relative links, as Common requires compliance with [IETF RFC 8288, Web Linking](http://tools.ietf.org/rfc/rfc8288.txt).

I will "unfix" the server so that this can be addressed.

**Comment by ghobona** [comment] 2021-02-25 11:15
@keshav-nangare 

The Relative Resolution algorithm is described in [Section 5.2](https://tools.ietf.org/html/rfc3986#section-5.2) of RFC 3986.

**Comment by keshav-nangare** [comment] 2021-03-01 09:40
@jerstlouis 

Can you please provide the service?

**Comment by jerstlouis** [comment] 2021-03-02 05:45
@keshav-nangare I have reverted to relative links (as well as to an extension for items as per #133) on our service so that this can be tested.
https://maps.ecere.com/ogcapi.
Thank you for looking into this issue!

**Comment by keshav-nangare** [comment] 2021-03-04 09:23
Updated test suite to handle relative links as per the Relative Resolution algorithm is described in [Section 5.2](https://tools.ietf.org/html/rfc3986#section-5.2) of RFC 3986. Please find the changes in #145 PR.

**Comment by jerstlouis** [comment] 2021-03-04 09:45
@keshav-nangare Would this also handle relative link fragments like `../` to go one level up, or `./` to start from the current resource?

**Comment by keshav-nangare** [comment] 2021-03-11 08:26
@dstenger @ghobona 

I have verified the changes with the service https://maps.ecere.com/ogcapi. According to the service implementation, it supports the "/" path present in the href element. Please check below for reference:

![image](https://user-images.githubusercontent.com/14732650/110757362-50983600-8271-11eb-97a3-c82bf6dc359e.png)

**Comment by jerstlouis** [comment] 2021-03-11 08:40
@keshav-nangare Sure on our service the relative links start at the root of the service, but for testing compliance of an arbitrary service, the resolution algorithm should fully support any kind of relative links as defined by RFC 3986, and an OGC API client should be ready to resolve any kind of relative links (unless we otherwise decide to impose limitations in this regard and clarify that in _OGC API - Common - Part 1: Core_ -- but that is currently not the case).

**Comment by ghobona** [comment] 2021-03-17 10:00
@jerstlouis 

The original issue has been fixed. Every executable test suite has to impose some limitations because we have finite resources. 

After merging the PR, we will close this issue (131) and it can be re-opened in the future if any developers volunteer to extend the URL resolution functionality.

**Closed** 2021-04-28 19:47 UTC
