### ISSUE TITLE
Wrong construction of feature path for implementations using file extensions

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ets-ogcapi-features10#133] opened 2021-01-21 21:57 UTC
The rules on how the test construct individual Feature requests are not clear and seem to not support ".{extension}" paths.
It does not seem to be using the OpenAPI description path "/collections/{collectionId}/items/{featureId}" but seems to be using the "items" relation type link which we had as
"https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/items.json"

and it constructed a path by adding /1 after the .json extension resulting in:

https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/items.json/1

however our server would have expected:

https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/items/1.json
or
https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/items/1?f=json
or
https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/items/1
with an "Accept: application/geo+json" header.

I had an extensive discussion with @pvretano who confirmed this to be a bug in the test.
However, this also seems to indicate that the "follow the link" approach is missing a proper mechanism to construct this path, and an update to Features could perhaps require a templated link to individual features (as used in _Tiles_ for example).

The Features 1.0 standard actually does mention the singular `item` relation type, but only in the list of relation types, not in any requirement or other text (whether normative or informative).
In a recent update to our server we have added new links using this relation type, templated with the `{featureId}` parameter:

```
{
   "rel" : "item",
   "type" : "application/geo+json",
   "title" : "ne_10m_admin_0_countries (individual feature as GeoJSON)",
   "href" : "https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/items/{featureId}?f=json",
   "templated" : true
},
```

which could also be:

```
{
   "rel" : "item",
   "type" : "application/geo+json",
   "title" : "ne_10m_admin_0_countries (individual feature as GeoJSON)",
   "href" : "https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/items/{featureId}.json",
   "templated" : true
},
```

I suggest that a future update to _Features_ could make the presence of such a link in the collection description document a requirement.

**Comment by dstenger** [comment] 2021-01-25 15:44
Thank you for reporting.

We will analyze the reported behavior.

**Comment by dstenger** [comment] 2021-01-25 15:49
I agree that https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/items.json/1 should not be constructed by the test suite.

Did you change the server behind this URL? Now, it seems to look different.

**Comment by jerstlouis** [comment] 2021-01-25 15:52
@dstenger yes, in order to pass the tests we have switched to `?f=json` instead of `.json` until this issue is resolved.

**Comment by ghobona** [comment] 2021-02-11 09:35
2021-02-11

@jerstlouis @pvretano the standard states that the path is `/items` and not `/items.json`. The API definition also clearly states that the path is `/items`. Therefore, the test suite is correct in expecting the implementation to be `/items`.

**Comment by jerstlouis** [comment] 2021-02-11 13:24
@ghobona What the test suite was trying to access is `https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/items.json/1`

The standard is supposed to allow different representations using different approaches, including an `f=` query parameter, or a file extension (as is practical for example for a static server that you would want to host on AWS S3).

See resolution at https://github.com/opengeospatial/ogcapi-features/issues/12#issuecomment-362308971

**Comment by ghobona** [comment] 2021-02-12 10:27
@jerstlouis I now see where the source of the issue is.

[Example 10](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_response_6) in the spec actually supports your approach. We'll update the ETS to support such URLs. Thanks.

**Comment by jerstlouis** [comment] 2021-02-12 14:11
@ghobona The root of the issue though in my opinion is a limitation/missing requirement in the _Features_ specs.
The only way that the test suite would be able to generate such a link is if the specs better defined the `"item"` relation type allowing for a templated reference, as we are now doing in our server with:

```
      {
         "rel" : "item",
         "type" : "application/geo+json",
         "title" : "ne_10m_admin_0_countries (individual feature as GeoJSON)",
         "href" : "https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/items/{featureId}.json",
         "templated" : true
      },
```

 (though right now it uses `?f=json`)

But the _Features_ specs only mentions in passing `"item"` without ever defining it in any requirement.

@pvretano would you like me to file an issue in _Features_ for this?

**Comment by cportele** [comment] 2021-02-12 14:55
There is nothing missing in the spec, AFAICT. The test suite can create a request to `https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/items/{featureId}` with an `Accept: application/geo+json` header. No need for the server to support format-specific URIs or for the client to know them.

**Comment by jerstlouis** [comment] 2021-02-12 15:07
@cportele At the very least that's not clearly communicated, but my understanding of the issue 12 resolution was that it accommodated that... What you described already worked in our server, but that's not what how the TEAM engine ended up doing.

See for example _Example 11. Links_ in 7.16.2
http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_response_7

```
Link: <http://data.example.org/collections/buildings/items/123.json>; rel="self"; type="application/geo+json"
Link: <http://data.example.org/collections/buildings/items/123.html>; rel="alternate"; type="text/html"
```

**Comment by cportele** [comment] 2021-02-12 15:25
It is clearly stated, see http://docs.opengeospatial.org/DRAFTS/17-069r4.html#encodings.

> Requirement /req/core/http implies that the encoding of a server response is determined using content negotiation as specified by the HTTP RFC.

Where there is an explicit link, that can be directly resolved, too, but guessing URLs is not safe - nor is it needed.

> Maybe what you're saying is that regardless of that being supported, the server must at minimum support /items/{featureId}, and that is the only thing that the TEAM engine should test?

Yes, unless the test suite is following an explicit link returned by the API, that is of course valid, too.

> But it still leaves a hole in the "follow the link" approach. The specifications is missing a templated link to individual features.

I do not see it as a hole:

- The URI template is already specified in the standard. 
- Features does not use templated links.
- Even, if the URI template is also included in the content, users will have to consult the API definition or the standard to be able to use the template.

I agree, that once URI templates are included in Common, it could be used in an example in Features, but that should be sufficient. If people feel that it would be helpful, there could also be a recommendation.

**Comment by dstenger** [comment] 2021-02-18 10:25
Unfortunately, we cannot reproduce the behavior anymore. Thus, I propose to close this issue for now.
@jerstlouis If this behavior is very important for you and should be fixed, can you please provide a test service again?

**Comment by jerstlouis** [comment] 2021-02-18 15:17
@dstenger Yes this is very important to fix in the test suite. I can revert our test service to feature the problem again, providing this is OK with the compliance program? (we did get our compliance status) @ghobona

**Comment by jerstlouis** [comment] 2021-03-02 05:46
@dstenger @keshav-nangare I have reverted to an extension for items (as well as to relative links as per #131) on our service so that this can be tested.
https://maps.ecere.com/ogcapi.
Thank you for looking into this issue!

**Comment by keshav-nangare** [comment] 2021-03-10 13:43
@dstenger @ghobona 

I have updated the test suite to handle ".{extension}" path.
eg. 
If the link is of type `/collections/{collectionId}/items.{extension}` will be converted into `/collections/{collectionId}/items/{featureId}.{extension}`.

**Comment by jerstlouis** [comment] 2021-03-10 13:57
@keshav-nangare Because Features does not make use of templated links (we included one now with `item` rel, but that is not specified in the standard), I think the only thing a client (including the test suite) can reliably test/use is access the standard fixed path (`/collections/{collectionId}/items/{featureId}`), and use content negotiation (`Accept: header`) to select an accepted format (e.g. GeoJSON), as mentioned by @cportele [above](https://github.com/opengeospatial/ets-ogcapi-features10/issues/133#issuecomment-778260734).

Anything else is just a special case (including what the test suite was previously doing by appending `/{feature ID}` to the rel `items` link). Additionally the 'all items' link is a completely different resource/path than the individual feature, so the link is really unrelated. Maybe @cportele or @pvretano could chime in on how the test suite should behave in this regard?

**Comment by cportele** [comment] 2021-03-12 10:17
> I think the only thing a client (including the test suite) can reliably test/use is access the standard fixed path (/collections/{collectionId}/items/{featureId}), and use content negotiation (Accept: header) to select an accepted format (e.g. GeoJSON)

Yes

**Closed** 2021-05-20 19:26 UTC
