### ISSUE TITLE
Error on build output: Error fetching URL: http://testng.org/javadocs/

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ets-ogcapi-features10#111] opened 2020-07-03 09:29 UTC
When trying to build the project (mvn package), I get the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) on project ets-ogcapi-features10: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - javadoc: error - Error fetching URL: http://testng.org/javadocs/
```

http://testng.org/javadocs/ indeed results in a 404 error.

It seems, when looking at https://testng.org/doc/, the javadoc has been moved to https://javadoc.jitpack.io/. The link at https://testng.org/doc/ to the javadoc is https://jitpack.io/com/github/cbeust/testng/master/javadoc/, but as ets-ogcapi-features10 is using TestNG testng-6.9.10, the correct link in the pom file is probably https://javadoc.jitpack.io/com/github/cbeust/testng/6.9.10/javadoc/

```xml
      <plugin>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>2.10.4</version>
        <configuration>
          <source>1.8</source>
          <docfilessubdirs>true</docfilessubdirs>
          <show>package</show>
          <links>
            <link>https://javadoc.jitpack.io/com/github/cbeust/testng/6.9.10/javadoc/</link>
          </links>
        </configuration>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

This same issue occurs also in ets-common, probably in other projects too.

**Comment by heidivanparys** [comment] 2020-07-03 10:51
A workaround for local use is to skip javadoc generation:

`mvn clean package -Dmaven.javadoc.skip=true`

**Comment by dstenger** [comment] 2020-07-03 11:50
Thank you for reporting.

However, I am able to build the javadoc and just get a warning (build is successful however):
```
...
[INFO] --- maven-javadoc-plugin:2.10.4:jar (attach-javadocs) @ ets-ogcapi-features10 ---
[INFO] 
Loading source files for package org.opengis.cite.ogcapifeatures10...
Loading source files for package org.opengis.cite.ogcapifeatures10.openapi3...
Loading source files for package org.opengis.cite.ogcapifeatures10.conformance...
Loading source files for package org.opengis.cite.ogcapifeatures10.general...
...
Generating /home/stenger/git/ets-ogcapi-features10/target/apidocs/index.html...
Generating /home/stenger/git/ets-ogcapi-features10/target/apidocs/overview-summary.html...
Generating /home/stenger/git/ets-ogcapi-features10/target/apidocs/help-doc.html...
1 warning
[WARNING] Javadoc Warnings
[WARNING] /home/stenger/git/ets-ogcapi-features10/src/main/java/org/opengis/cite/ogcapifeatures10/util/JsonUtils.java:215: warning: no @param for rels
[WARNING] public static List<String> findLinksWithoutRelOrType( List<Map<String, Object>> links, Set<String> rels ) {
[WARNING] ^
[INFO] Building jar: /home/stenger/git/ets-ogcapi-features10/target/ets-ogcapi-features10-1.1-SNAPSHOT-javadoc.jar
...
```

What Maven and Java versions are you using for the build?

**Comment by heidivanparys** [comment] 2020-07-03 14:44
I get errors instead of warnings, and a failed build:

```
git log --oneline -5

54a880e (HEAD -> master, upstream/master, origin/master, origin/HEAD, generate_html_report) [maven-release-plugin] prepare for next development iteration
a8af0d6 (tag: 1.0) [maven-release-plugin] prepare release 1.0
fdf60b3 Add release notes for version 1.0
035206c Merge pull request #104 from ghobona/20200320-final-review-to-production
a629365 Updated screenshots from WFS3 to OGC API - Features

mvn --version

Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: C:\OtherPrograms\apache-maven-3.6.1\bin\..
Java version: 13.0.3, vendor: N/A, runtime: C:\Program Files\ojdkbuild\java-13-openjdk-13.0.3-1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

mvn clean package -Dsource=8 -Dmaven.test.skip=true

[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< org.opengis.cite:ets-ogcapi-features10 >---------------
[INFO] Building OGC API-Features 1.0 Conformance Test Suite 1.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[...]
[INFO]
[INFO] >>> maven-javadoc-plugin:2.10.4:javadoc > generate-sources @ ets-ogcapi-features10 >>>
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ ets-ogcapi-features10 ---
[INFO] ShortRevision tag detected. The value is '10'.
[INFO] Executing: cmd.exe /X /C "git rev-parse --verify --short=10 HEAD"
[INFO] Working directory: C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10
[INFO] Storing buildNumber: 54a880ec83 at timestamp: 1593786981675
[INFO] Storing buildScmBranch: master
[INFO]
[INFO] <<< maven-javadoc-plugin:2.10.4:javadoc < generate-sources @ ets-ogcapi-features10 <<<
[INFO]
[INFO] 'generate-sources' forked phase execution for maven-javadoc-plugin:javadoc report preparation done
[INFO] 1 report configured for maven-javadoc-plugin:2.10.4: javadoc
[INFO] Rendering site with default locale English (en)
[INFO] Rendering content with org.apache.maven.skins:maven-fluido-skin:jar:1.5 skin.
[INFO] Rendering 3 Doxia documents: 3 asciidoc
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.runtime.encoding.EncodingService (file:/C:/Users/B004114/.m2/repository/org/jruby/jruby-complete/9.1.17.0/jruby-complete-9.1.17.0.jar) to field java.io.Console.cs
WARNING: Please consider reporting this to the maintainers of org.jruby.runtime.encoding.EncodingService
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Generating "Licenses" report      --- maven-project-info-reports-plugin:2.9:license
[INFO] Generating "Issue Management" report --- maven-project-info-reports-plugin:2.9:issue-tracking
[INFO] Generating "JavaDocs" report      --- maven-javadoc-plugin:2.10.4:javadoc
[INFO]
Loading source files for package org.opengis.cite.ogcapifeatures10.apidefinition...
Loading source files for package org.opengis.cite.ogcapifeatures10.collections...
Loading source files for package org.opengis.cite.ogcapifeatures10...
Loading source files for package org.opengis.cite.ogcapifeatures10.conformance...
Loading source files for package org.opengis.cite.ogcapifeatures10.general...
Loading source files for package org.opengis.cite.ogcapifeatures10.landingpage...
Loading source files for package org.opengis.cite.ogcapifeatures10.openapi3...
Loading source files for package org.opengis.cite.ogcapifeatures10.util...
Constructing Javadoc information...
Standard Doclet version 13.0.3
Building tree for all the packages and classes...
Generating C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10\target\site\apidocs\org\opengis\cite\ogcapifeatures10\CommandLineArguments.html...
[...]
Generating C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10\target\site\apidocs\help-doc.html...
1 error
1 warning
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:40 min
[INFO] Finished at: 2020-07-03T16:36:57+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.7.1:jar (site-package) on project ets-ogcapi-features10: Error generating maven-javadoc-plugin:2.10.4:javadoc report:
[ERROR] Exit code: 1 - javadoc: error - Error fetching URL: http://testng.org/javadocs/
[ERROR] C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10\src\main\java\org\opengis\cite\ogcapifeatures10\util\JsonUtils.java:215: warning: no @param for rels
[ERROR]     public static List<String> findLinksWithoutRelOrType( List<Map<String, Object>> links, Set<String> rels ) {
[ERROR]                                ^
[ERROR]
[ERROR] Command line was: "C:\Program Files\ojdkbuild\java-13-openjdk-13.0.3-1\bin\javadoc.exe" @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in 'C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10\target\site\apidocs' dir.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by ghobona** [comment] 2020-07-06 17:20
I encountered the same error.

```
1 error
1 warning
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  39.793 s
[INFO] Finished at: 2020-07-06T18:15:33+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.7.1:jar (site-package) on project ets-ogcapi-features10: Error generating maven-javadoc-plugin:2.10.4:javadoc report: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR] /Users/ogccite/Documents/GitHub/ets-ogcapi-features10/src/main/java/org/opengis/cite/ogcapifeatures10/util/JsonUtils.java:215: warning: no @param for rels
[ERROR]     public static List<String> findLinksWithoutRelOrType( List<Map<String, Object>> links, Set<String> rels ) {
[ERROR]                                ^
[ERROR] 
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/Users/ogccite/Documents/GitHub/ets-ogcapi-features10/target/site/apidocs' dir.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

@lgoltz @keshav-nangare Any ideas of what the cause might be?

**Comment by ghobona** [comment] 2020-07-06 19:46
Fixed by PR https://github.com/opengeospatial/ets-ogcapi-features10/pull/115.

```
  [INFO] Building jar: /Users/ogccite/Documents/GitHub/ets-ogcapi-features10/target/ets-ogcapi-features10-1.1-SNAPSHOT-javadoc.jar
  [INFO] 
  [INFO] --- maven-assembly-plugin:2.6:single (default) @ ets-ogcapi-features10 ---
  [INFO] Reading assembly descriptor: /Users/ogccite/Documents/GitHub/ets-ogcapi-features10/src/assembly/deps.xml
  [INFO] Reading assembly descriptor: /Users/ogccite/Documents/GitHub/ets-ogcapi-features10/src/assembly/ctl-scripts.xml
  [INFO] Adding site directory to assembly : /Users/ogccite/Documents/GitHub/ets-ogcapi-features10/target/site
  [INFO] Reading assembly descriptor: /Users/ogccite/Documents/GitHub/ets-ogcapi-features10/src/assembly/aio.xml
  [INFO] Building zip: /Users/ogccite/Documents/GitHub/ets-ogcapi-features10/target/ets-ogcapi-features10-1.1-SNAPSHOT-deps.zip
  [INFO] Building tar: /Users/ogccite/Documents/GitHub/ets-ogcapi-features10/target/ets-ogcapi-features10-1.1-SNAPSHOT-deps.tar.gz
  [WARNING] The assembly descriptor contains a filesystem-root relative reference, which is not cross platform compatible /site
  [INFO] Building zip: /Users/ogccite/Documents/GitHub/ets-ogcapi-features10/target/ets-ogcapi-features10-1.1-SNAPSHOT-ctl.zip
  [INFO] Building jar: /Users/ogccite/Documents/GitHub/ets-ogcapi-features10/target/ets-ogcapi-features10-1.1-SNAPSHOT-aio.jar
  [INFO] ------------------------------------------------------------------------
  [INFO] BUILD SUCCESS
  [INFO] ------------------------------------------------------------------------
  [INFO] Total time:  20.190 s
  [INFO] Finished at: 2020-07-06T20:42:00+01:00
  [INFO] ------------------------------------------------------------------------
```

**Comment by heidivanparys** [comment] 2020-07-07 11:55
Update:

```
java --version
openjdk 13.0.3 2020-04-14
OpenJDK Runtime Environment 19.9 (build 13.0.3+3)
OpenJDK 64-Bit Server VM 19.9 (build 13.0.3+3, mixed mode, sharing)
```

![billede](https://user-images.githubusercontent.com/11427611/86773187-9acb7680-c055-11ea-847f-5739c8f58553.png)

See also https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-13-openjdk-13.0.3.3-1

### Master branch

When taking the code from the master branch:

```
git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

mvn clean javadoc:javadoc -Dsource=8
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< org.opengis.cite:ets-ogcapi-features10 >---------------
[INFO] Building OGC API-Features 1.0 Conformance Test Suite 1.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ets-ogcapi-features10 ---
[INFO] Deleting C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10\target
[INFO]
[INFO] >>> maven-javadoc-plugin:2.10.4:javadoc (default-cli) > generate-sources @ ets-ogcapi-features10 >>>
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ ets-ogcapi-features10 ---
[INFO] ShortRevision tag detected. The value is '10'.
[INFO] Executing: cmd.exe /X /C "git rev-parse --verify --short=10 HEAD"
[INFO] Working directory: C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10
[INFO] Storing buildNumber: 54a880ec83 at timestamp: 1594121314137
[INFO] Storing buildScmBranch: master
[INFO]
[INFO] <<< maven-javadoc-plugin:2.10.4:javadoc (default-cli) < generate-sources @ ets-ogcapi-features10 <<<
[INFO]
[INFO]
[INFO] --- maven-javadoc-plugin:2.10.4:javadoc (default-cli) @ ets-ogcapi-features10 ---
[INFO]
Loading source files for package org.opengis.cite.ogcapifeatures10.apidefinition...
Loading source files for package org.opengis.cite.ogcapifeatures10.collections...
Loading source files for package org.opengis.cite.ogcapifeatures10...
Loading source files for package org.opengis.cite.ogcapifeatures10.conformance...
Loading source files for package org.opengis.cite.ogcapifeatures10.general...
Loading source files for package org.opengis.cite.ogcapifeatures10.landingpage...
Loading source files for package org.opengis.cite.ogcapifeatures10.openapi3...
Loading source files for package org.opengis.cite.ogcapifeatures10.util...
Constructing Javadoc information...
Standard Doclet version 13.0.3
Building tree for all the packages and classes...
Generating C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10\target\site\apidocs\org\opengis\cite\ogcapifeatures10\CommandLineArguments.html...
[...]
Generating C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10\target\site\apidocs\help-doc.html...
1 error
1 warning
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  35.341 s
[INFO] Finished at: 2020-07-07T13:29:00+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:javadoc (default-cli) on project ets-ogcapi-features10: An error has occurred in JavaDocs report generation:
[ERROR] Exit code: 1 - javadoc: error - Error fetching URL: http://testng.org/javadocs/
[ERROR] C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10\src\main\java\org\opengis\cite\ogcapifeatures10\util\JsonUtils.java:215: warning: no @param for rels
[ERROR]     public static List<String> findLinksWithoutRelOrType( List<Map<String, Object>> links, Set<String> rels ) {
[ERROR]                                ^
[ERROR]
[ERROR] Command line was: "C:\Program Files\ojdkbuild\java-13-openjdk-13.0.3-1\bin\javadoc.exe" @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in 'C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10\target\site\apidocs' dir.
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

The important line is `[ERROR] Exit code: 1 - javadoc: error - Error fetching URL: http://testng.org/javadocs/`

When I look at the effective POM (`mvn help:effective-pom -Dsource=8 -Dverbose=true`), the lines that contain http://testng.org/javadocs/ say either `<link>http://testng.org/javadocs/</link>  <!-- org.opengis.cite:ets-common:9, line 260 -->`
or `<link>http://testng.org/javadocs/</link>  <!-- org.opengis.cite:ets-ogcapi-features10:1.1-SNAPSHOT, line 115 -->`

### testng_javadoc branches

When applying the following changes:

1. In ets-common: https://github.com/opengeospatial/ets-common/compare/master...heidivanparys:testng_javadoc
2. In ets-ogcapi-features10: https://github.com/opengeospatial/ets-ogcapi-features10/compare/master...heidivanparys:testng_javadoc

the build succeeds (I only get a warning on a missing `@param` in `JsonUtils.java`):

```
git checkout testng_javadoc
Switched to branch 'testng_javadoc'
Your branch is up to date with 'origin/testng_javadoc'.

mvn clean javadoc:javadoc -Dsource=8
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< org.opengis.cite:ets-ogcapi-features10 >---------------
[INFO] Building OGC API-Features 1.0 Conformance Test Suite 1.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ets-ogcapi-features10 ---
[INFO] Deleting C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10\target
[INFO]
[INFO] >>> maven-javadoc-plugin:2.10.4:javadoc (default-cli) > generate-sources @ ets-ogcapi-features10 >>>
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ ets-ogcapi-features10 ---
[INFO] ShortRevision tag detected. The value is '10'.
[INFO] Executing: cmd.exe /X /C "git rev-parse --verify --short=10 HEAD"
[INFO] Working directory: C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10
[INFO] Storing buildNumber: c3752f485c at timestamp: 1594121564338
[INFO] Storing buildScmBranch: testng_javadoc
[INFO]
[INFO] <<< maven-javadoc-plugin:2.10.4:javadoc (default-cli) < generate-sources @ ets-ogcapi-features10 <<<
[INFO]
[INFO]
[INFO] --- maven-javadoc-plugin:2.10.4:javadoc (default-cli) @ ets-ogcapi-features10 ---
[INFO]
Loading source files for package org.opengis.cite.ogcapifeatures10.apidefinition...
Loading source files for package org.opengis.cite.ogcapifeatures10.collections...
Loading source files for package org.opengis.cite.ogcapifeatures10...
Loading source files for package org.opengis.cite.ogcapifeatures10.conformance...
Loading source files for package org.opengis.cite.ogcapifeatures10.general...
Loading source files for package org.opengis.cite.ogcapifeatures10.landingpage...
Loading source files for package org.opengis.cite.ogcapifeatures10.openapi3...
Loading source files for package org.opengis.cite.ogcapifeatures10.util...
Constructing Javadoc information...
Standard Doclet version 13.0.3
Building tree for all the packages and classes...
Generating C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10\target\site\apidocs\org\opengis\cite\ogcapifeatures10\CommandLineArguments.html...
[...]
Generating C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10\target\site\apidocs\help-doc.html...
1 warning
[WARNING] Javadoc Warnings
[WARNING] C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10\src\main\java\org\opengis\cite\ogcapifeatures10\util\JsonUtils.java:215: warning: no @param for rels
[WARNING] public static List<String> findLinksWithoutRelOrType( List<Map<String, Object>> links, Set<String> rels ) {
[WARNING] ^
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.675 s
[INFO] Finished at: 2020-07-07T13:33:11+02:00
[INFO] ------------------------------------------------------------------------
```

**Closed** 2020-10-08 18:32 UTC
