### ISSUE TITLE
Creating a 7th session says "Executing Test" spinning forever

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ets-ogcapi-features10#186] opened 2021-11-16 17:24 UTC
(NOTE: Unsure whether this is specific to the OGC API - Features ETS or if it should be moved to the [Team Engine repository](https://github.com/opengeospatial/teamengine))
**Describe the bug**
Trying to create a new session to test our implementation, creating a new session was spinning forever saying "Executing Tests" before having selected a server on which to execute the test and never ends. Cleaning up 2 previous sessions seems to avoid the issue. This is confusing and buggy behavior and the issues related to space limitation should be resolved or reported properly as the user needing to clear previous sessions before creating a new one.

**To Reproduce**
Create multiple sessions at https://cite.opengeospatial.org/teamengine or https://cite.opengeospatial.org/te2 and execute tests selecting "OGC API - Features" until creating a new one just spins forever.

**Expected behavior**
Creating a new session should either always work, or an error should be given letting the user know that space limitations are exceeded and sessions need to be deleted before creating a new one.

**Comment by dstenger** [comment] 2021-11-16 19:01
Thank you for reporting.
So, you are creating the sessions one after another and not simultaneously? If that is the case, there should be no restrictions.
We will do further investigation.

**Comment by jerstlouis** [comment] 2021-11-16 19:05
@dstenger That was just creating a single session, but I already had 6 sessions in my account. Is there some storage limitations associated with a single account, or with the overall capacity of the TeamEngine deployments?

Deleting previous sessions got past this error somehow.

To clarify, this was before even selecting our server to test. The Console window had not popped up.

I was just able to reproduce it. The first time it worked (brought me to the page where I can select our server). The second time it happened again, no Console popup.

And now I got this 500 error:

https://cite.opengeospatial.org/te2/viewSessionLog.jsp?session=undefined&stop=true&t=1637089446398

HTTP Status 500 - java.io.FileNotFoundException: /srv/local/teamengine-te2/TE_BASE/users/jerstlouis4/undefined/session.xml (No such file or directory)
type Exception report

message java.io.FileNotFoundException: /srv/local/teamengine-te2/TE_BASE/users/jerstlouis4/undefined/session.xml (No such file or directory)

description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.io.IOException: java.io.FileNotFoundException: /srv/local/teamengine-te2/TE_BASE/users/jerstlouis4/undefined/session.xml (No such file or directory)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:467)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
root cause

java.io.FileNotFoundException: /srv/local/teamengine-te2/TE_BASE/users/jerstlouis4/undefined/session.xml (No such file or directory)
	java.io.FileInputStream.open0(Native Method)
	java.io.FileInputStream.open(FileInputStream.java:195)
	java.io.FileInputStream.<init>(FileInputStream.java:138)
	java.io.FileInputStream.<init>(FileInputStream.java:93)
	sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	com.occamlab.te.web.TestSession.load(TestSession.java:101)
	org.apache.jsp.viewSessionLog_jsp._jspService(viewSessionLog_jsp.java:254)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.63 logs.

**Comment by jerstlouis** [comment] 2021-11-16 19:07
@dstenger Now I get a 500 right after logging in to te2 with my account:

https://cite.opengeospatial.org/te2/viewSessions.jsp

HTTP Status 500 - javax.servlet.ServletException: org.xml.sax.SAXParseException; Premature end of file.
type Exception report

message javax.servlet.ServletException: org.xml.sax.SAXParseException; Premature end of file.

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: javax.servlet.ServletException: org.xml.sax.SAXParseException; Premature end of file.
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:556)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:462)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
root cause

javax.servlet.ServletException: org.xml.sax.SAXParseException; Premature end of file.
	org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:916)
	org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:845)
	org.apache.jsp.viewSessions_jsp._jspService(viewSessions_jsp.java:293)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
root cause

org.xml.sax.SAXParseException; Premature end of file.
	org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	com.occamlab.te.web.TestSession.load(TestSession.java:101)
	org.apache.jsp.viewSessions_jsp._jspService(viewSessions_jsp.java:206)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.63 logs.

Apache Tomcat/7.0.63

**Comment by dstenger** [comment] 2021-11-16 19:32
Thanks for reporting.
The errors were related to the environment and should be fixed by now.
Can you please check if your reported problems are solved?

**Comment by jerstlouis** [comment] 2021-11-16 19:34
@dstenger No, I still get a 500 error right after signing in.

Also in my product certification I do not see any session listed.
Earlier I was only seeing sessoin from /te2, not those from /teamengine.

**Comment by dstenger** [comment] 2023-05-10 10:19
@jerstlouis Did you resolve the issue by creating a new user? If the problem is still occurring, can you please provide the user name so that we can check it?

**Closed** 2023-10-18 11:02 UTC
