### ISSUE TITLE
Error on build output

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ets-ogcapi-features10#106] opened 2020-03-30 08:37 UTC
Building the code with Maven (`mvn package`) on a Windows machine gives the following error (the build itself succeeds):

```
[ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with slash) /site
[INFO] Building zip: C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10\target\ets-ogcapi-features10-1.1-SNAPSHOT-ctl.zip
[INFO] Building jar: C:\Users\B004114\Documents\GitHub\heidivanparys\ets-ogcapi-features10\target\ets-ogcapi-features10-1.1-SNAPSHOT-aio.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by dstenger** [comment] 2020-03-31 08:58
Thank you for reporting.
@keshav-nangare Can you please take a look at this problem?

**Comment by keshav-nangare** [comment] 2020-04-23 09:05
@dstenger 

I am able to reproduce this issue on Mac OS as a warning. I have fixed this issue by updating the assembly descriptor file assembly/ctl-scripts.xml. There is one element `<includeSiteDirectory>` which is the cause of this error message. I have removed this flag and added extra logic to include site directory in build zip.

`[WARNING] The assembly descriptor contains a filesystem-root relative reference, which is not cross platform compatible /site`

I have not tested these changes on the windows machine but hopefully, it will get resolve on Windows as well.

**Comment by keshav-nangare** [comment] 2020-04-23 09:05
Fixed with this PR: #110.

**Comment by dstenger** [comment] 2020-04-29 08:15
@keshav-nangare Can you please try to use `<siteDirectory>${project.build.directory}/site</siteDirectory>` parameter in assembly plugin`

**Comment by keshav-nangare** [comment] 2020-05-05 06:39
@dstenger 

I have tried to use `siteDirectory` parameter but didn't find any references/example.

**Closed** 2020-10-08 18:28 UTC

**Comment by apjanke** [comment] 2022-09-15 05:07
FWIW, I'm [having the same problem with my "SLF4M-Jankalog" project](https://github.com/janklab/slf4m-jankalog/issues/22), and am curious if there's a better resolution here. (Sorry to bug you here, but this bug report is one of the few decent things on the web that I was able to google up for this specific problem.)

I found some reference doco for the maven-site-assembly plugin:

* [assembly 2.6 `assembly:assembly` mojo parameter reference](https://maven.apache.org/plugins-archives/maven-assembly-plugin-2.6/assembly-mojo.html), which I think documents the `<configuration>` format in the POM
* [assembly 3.4.2 main page](https://maven.apache.org/plugins/maven-assembly-plugin/assembly.html), which documents the `<assembly>` format for the reference XML file, but not POM's `<configuration>`' format
* [assembly 3.4.2 `assembly:single` mojo parameter referenc](https://maven.apache.org/plugins/maven-assembly-plugin/single-mojo.html), which I think documents the `<configuration>` in the POM

None of those have a `<siteDirectory>` element/parameter that I can see.

But if I look at the Javadoc for some classes in the assembly 3.4.2 plugin's implmentation, there are Java getter/setters for a `siteDirectory` JavaBeans property in some of its classes.

* [assembly 3.4.2 class `org.apache.maven.plugins.assembly.mojos.SingleAssemblyMojo`](https://maven.apache.org/plugins-archives/maven-assembly-plugin-3.4.2/apidocs/index.html?org/apache/maven/plugins/assembly/mojos/SingleAssemblyMojo.html)
* [assembly 3.4.2 class `org.apache.maven.plugins.assembly.mojos.AbstractAssemblyMojo`](https://maven.apache.org/plugins-archives/maven-assembly-plugin-3.4.2/apidocs/index.html?org/apache/maven/plugins/assembly/mojos/SingleAssemblyMojo.html)
* [assembly 3.4.2 interface `org.apache.maven.plugins.assembly.AssemblerConfigurationSource`](https://maven.apache.org/plugins-archives/maven-assembly-plugin-3.4.2/apidocs/org/apache/maven/plugins/assembly/AssemblerConfigurationSource.html)

Those class's other properties look like the correspond to the elements in the POM `<configuration>` section for `maven-assembly-plugin`. So I bet that's where it goes. And IntelliJ's POM XML Intellisense feature seems to agree:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/2618447/190318396-bd822f12-af3f-4a67-8bb3-fed4b9c61a55.png">

I don't know why `siteDirectory` doesn't show up in the more user-facing documentation above. Is this actually an internal-use method for the plugin itself, and its omission was intentional? Or is it a documentation bug in whatever's generating those web pages? (And why are the "mojo" documentation pages for the `<configuration>` sections of Maven plugins so hard to find? They don't seem to be linked anywhere in the navigation stuff in the plugins' main pages like [this `maven-compiler-plugin` page](https://maven.apache.org/components/plugins/maven-compiler-plugin/); I either have to get lucky with a link in the body text of the plugin page, or google for "maven-\<pluginname\>-plugin mojo".)

I re-enabled `<includeSiteDirectory>true</includeSiteDirectory>`, and stuck this in the assembly POM `<configuration>` section for my project:
```
        <configuration>
          <siteDirectory>/some/nonexistent/bogus/path</siteDirectory>
```
and it started kicking out this error:
```
[INFO] --- maven-assembly-plugin:2.6:assembly (default-cli) @ log4j ---
[INFO] Reading assembly descriptor: src/assembly/bin.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.707 s
[INFO] Finished at: 2022-09-15T01:05:11-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:assembly (default-cli) on project log4j: site did not exist in the target directory - please run site:site before creating the assembly: Mojo configuration is invalid: site did not exist in the target directory - please run site:site before creating the assembly -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

So I think that's the right place for `<siteDirectory>`; but I dunno how to use it here.
